### ISSUE TITLE
Add missing tags fields

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-query#22]
Some tags fields are hidden and not exposed through the drilldown menu.

The full list of tags fields is in po/tags/tags.pot

Currently missing:

checkers
cities
codes
correctors
debug
editors
informers
ingredients_original
ingredients_from_palm_oil
ingredients_that_may_be_from_palm_oil
known_nutrients
last_image_dates
numbers_of_ingredients
nutrient_levels
packager_codes
periods_after_opening
photographers
pnns_groups_1
pnns_groups_2
purchase_places
unknown_nutrients
contributors
last_check_dates
popularity
ingredients_analysis
data_quality_bugs
data_quality_warnings
data_quality_warnings_producers
data_quality_errors_producers
possible_improvements
imports
categories_properties
owners
food_groups
weighers
packaging_shapes
packaging_materials
packaging_recycling
nutriscore
nutriscore_2021
nutriscore_2023

Are there any performance issues or other issues associated with adding all those fields?

**Comment by john-gom** [comment]
Hi @stephanegigandet . Adding more tags will increase the OFF-query PostgreSQL database size and slow down the time it takes to do full / incremental loads but shouldn't have any impact on specific queries, i.e. adding more tags won't slow down queries on tags we already implement

**Comment by stephanegigandet** [comment]
Hi @john-gom , good, in that case I think we should add all missing tags.

**Comment by john-gom** [comment]
I've created a PR to add most of the mentioned tags. I was not able to implement the following:

 - known_nutrients: Not found in PO
 - numbers_of_ingredients: This is a scaler
 - packager_codes: This is a hash
 - contributors: Think this is already covered by editors
 - data_quality_warnings_producers, data_quality_errors_producers, possible_improvements, imports, categories_properties_tags: Can't see these in PO
 - owners: This is a scalar
