### ISSUE TITLE
Logs edit events in openfoodfacts-query

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/openfoodfacts-query#33]
### Problem

We started https://github.com/openfoodfacts/openfoodfacts-events/ but discussing together we realize it would be better to store events in openfoodfacts-query as it would enable crossing events with facets.

### Solution

Log events in openfoodfacts-query.

Add a table that correspond to the changes.sto with useful information: date, user, device, changed fields.

Add events from redis stream.

Add an API to query that with filtering options.

After that we might want to log more events:
* scans
* producers imports

**Comment by john-gom** [comment]
Testing view performance. Without an index a query for a month of data takes about 3 minutes, e.g.:

select * from product_update_view where updated_day > '2023-11-01' and updated_day < '2023-12-01';

**Comment by alexgarel** [comment]
@john-gom do you use partitioned tables to partition the tables by say year (or year-month) ?

@cquest might have an opinion on this, but I think this could help. We are in a typical case of non moving temporal data, there are a lot of tricks we might be able to apply to them.
