### ISSUE TITLE
Unconfigured postgresql

### ISSUE THREAD

**Issue by cquest** [openfoodfacts/openfoodfacts-query#48]
Postgresql is not configured and thus not taking advantages of availables ressources:
- shared_buffers default of 128MB does not alet PG keep frequently used data (like indices) to remain in RAM
- work_mem default makes PG create temporary tables on disk instead of RAM

On the production container, we could have values likes:
- shared_buffers=16G (will reduce reads)
- work_mem=1G (will reduce writes)
-

**Comment by john-gom** [comment]
Thanks @cquest . Will we need to increase the smh_size in docker to accommodate this? In production this is currently set to 1GB

**Comment by john-gom** [comment]
It looks like shared_buffers is not allocated from shm_size (see comment on answer to https://dba.stackexchange.com/questions/275378/dev-shm-size-recommendation-for-postgres-database-in-docker)
