### ISSUE TITLE
Switch from json to jsonb

### ISSUE THREAD

**Issue by cquest** [openfoodfacts/openfoodfacts-query#49]
jsonb has many benefits :
- does parsing once during record creation,
- it can also be indexed
- takes less storage space

> "In general, most applications should prefer to store JSON data as jsonb, unless there are quite specialized needs, such as legacy assumptions about ordering of object keys." - postgresql's documentation

**Comment by john-gom** [comment]
Hi @cquest . I did initially try using JSONB but there were two main factors that made me stick with JSON:

1. This initial storage time is increased as Postgres needs to parse the supplied JSON
2. Queries performed by off-query do not use the JSON data, they use the relational model, so having the pre-parsed JSONB has no benefit

**Comment by alexgarel** [comment]
@john-gom reduce storage size can be considered enough of a benefice for the time spent parsing.

**Comment by john-gom** [comment]
Hi @alexgarel . I am working on a branch on this (although paused for Keycloak) so that the full Product JSON is only loaded into a temporary table for each batch of products being imported, i.e. not keep the original JSON at all. This should significantly reduce the database size

**Comment by john-gom** [comment]
This was completed indirectly when we stopped storing product data permanently and just load via a temporary table (which uses JSONB)
